src/app/assets/stylesheets/shared.css.scss
src/app/views/layouts/application.html.erb

We currently don't have any way to get back to the landing page in the app. And clicking on the upper-left most icon takes you off the site. 
BEFORE: 
We moved the bar/demo icons to the right and made the first star icon a 'go to home' link. 
AFTER:

Move primary nav around to include a link to the sessionizer root path.

---

src/.rvmrc

.rvmrc file unneeded & specifies wrong version

---

src/app/assets/stylesheets/shared.css.scss
src/app/helpers/application_helper.rb
src/spec/helpers/application_helper_spec.rb

Prevents session descriptions & user bios from being able to clobber the rest of the page. (We currently have a couple of bios that are doing that with unclosed tags and bad style attributes.)
Also, although I haven’t investigated, the lack of sanitizing is probably a security risk.
I was a little concerned about the performance cost of this aggressive sanitizing on the schedule page, which invisibly renders all the session descs & bios in one huge blob, but some quick tests suggest it adds negligible time.
Fixes #70.

Sanitize markdown

---

src/app/controllers/events_controller.rb
src/app/models/session.rb
src/config/routes.rb
src/spec/controllers/events_controller_spec.rb

EventsController was removed in 432a205c608d8621996ea2a7ed7991f51317bc13 due to being unused. Turns out that wasn't quite true.
Should _actually_ fix #75.

Restore Event JSON export

---

src/lib/scheduling/context.rb
src/lib/scheduling/schedule.rb
src/lib/tasks/app.rake

Sessions that are entered before the scheduler are run are now
immutable with regards to their timeslot. They will not get scheduled
elsewhere.  This enable you to add sessions that have to be in a
certain place at a certain time. The scheduler pays no-attention to them,
so you only want to place them into Timeslots where schedulable is
false.  For example you may place a "Presenters Luncheon, rm 123"
during the  "Lunch" timeslot.
Also added a rake task `app:clear_schedule` This enables the generated
schedule to be cleared so an alternate schedule can be generated.

Allow unschedulable sessions

---

src/db/migrate/20150920192518_add_schedulable_to_room.rb
src/db/schema.rb
src/lib/scheduling/context.rb

Unschedulable rooms can be used for events on the schedule but that you
don't want to be automatically scheduled by the annealer.  For example,
we could add the cafeteria as a room, but we don't want to schedule
sessions there.  We could "hard code" an event (i.e. BOF meetup) to happen
in the cafeteria though.

Allow rooms to be schedulable

---

src/app/controllers/sessions_controller.rb
src/spec/controllers/sessions_controller_spec.rb

Our 2016 db now contains 2015 event data ... woot.

Allow export of previous year sessions

---

src/app/controllers/schedules_controller.rb
src/app/models/event.rb
src/spec/controllers/schedules_controller_spec.rb

Move the caching of current_event and schedule into the controller layer
This allows you to use a cache and have all processes return the same
values (unless you're using memory store).

Use Rails caching for current_event

---

src/app/assets/stylesheets/shared.css.scss
src/app/controllers/pages_controller.rb
src/app/controllers/sessions_controller.rb
src/app/models/session.rb
src/app/views/pages/_category_grid.html.erb
src/app/views/pages/_sessions.html.erb
src/app/views/sessions/index.html.erb
src/spec/features/interest_gathering_spec.rb

Some quick & dirty changes to ease (though not totally address) #85.
Background: the current UI shows just a few sessions _most recent_ first, and the “all sessions” page shows them _least recent_ first. This favors the very first and last sessions created, and leaves sessions in the middle a bit undervoted. The oldest ones get especially overvoted, in part because they're visible longer, and in part because you have to scroll so far on the “all sessions” page to see the newer ones.
I suspect that we'd get better data for the scheduler if we displayed a more even sampling of sessions in the UI. I made a few of the easier changes that might address that:
- Sessions home now shows a random sampling of sessions first, then recently added, then by category. Those first two are shorter than …

Random session order

---

.gitignore

This follows the practice of the generator in Rails 5 and fixes the build error:
```
Failure/Error: before { Rails.cache.clear }
Errno::ENOENT:
No such file or directory @ dir_initialize -
/home/travis/build/minnestar/sessionizer/src/tmp/cache/
```

Add the tmp/ dir to the repository as an empty directory

---

src/app/views/sessions/index.html.erb

Using the built in cache key so that when a session is removed the cache is poisoned.  See http://blog.bigbinary.com/2016/02/02/activerecord-relation-cache-key.html

Update cache key for session list

---

src/config/application.rb

http://blog.bigbinary.com/2016/08/29/rails-5-disables-autoloading-after-booting-the-app-in-production.html

Eager load in rails 5

---

src/app/controllers/user_sessions_controller.rb
src/app/views/pages/_sessions.html.erb
src/app/views/sessions/index.html.erb

Alex noted a bug where sessions would show as favorited (Minnestar icon next to them) even though the user hadn't favorited them. I believe this fixes the issue.
I also threw in a fix for a server error when logging out redundantly (log out, back, log out again).

Session cache fix

---

src/app/assets/stylesheets/schedule-mobile.css.sass
src/app/assets/stylesheets/schedule-print.css.sass
src/app/assets/stylesheets/schedule.css.sass
src/app/controllers/admin/admin_controller.rb
src/app/controllers/schedules_controller.rb
src/app/helpers/schedules_helper.rb
src/app/models/session.rb
src/app/views/layouts/schedule.html.erb
src/app/views/timeslots/_timeslot.html.haml
src/config/application.rb

A grab bag:
- Schedule page now works even if sessions don’t have rooms yet. This is in anticipation of getting the schedule out early this year, and assigning rooms only later.
- The schedule — and the whole app! — should always show dates in Central Time, regardless of the user’s device’s time zone.
- Fixed broken CSS/JS includes (probably got hosed during the Rails 5 migration?).
- Mopped up some layout stuff that got messy with incremental fixes over the years.
- Fixed broken URL in http → https admin redirect. (Should we force https site-wide?)

Schedule UI improvements

---

src/app/assets/stylesheets/schedule.css.sass
src/app/controllers/user_sessions_controller.rb
src/app/views/schedules/index.html.haml

This adds a link to the top of the schedule mentioning that you can now actually see your favorited sessions if you log in. People are likely to have logged in on their desktop but be checking the schedule from mobile, and not realize it's actually worth bothering to log in now.
Innocent little change, and I’m going to go ahead and merge it — but leaving this PR here for any discussion.

Prompt users to log in to see votes on schedule

---

src/app/controllers/application_controller.rb
src/app/controllers/sessions_controller.rb
src/app/models/sessions_json_builder.rb
src/app/views/schedules/index.html.haml
src/app/views/sessions/index.html.erb

Somebody out there is polling `/sessions.json`, and it takes as much as 9 seconds per request.
This PR stops the database explosion that controller causes (for a ~4.5x speedup), and also caches the response (for a ~100x speedup when the cache is fresh).
I'm going to deploy this tonight rather than right before the event starts tomorrow morning, but I’m leaving this PR in case anybody else is having fun reviewing code on a Friday night.

Performance improvements and caching for /sessions.json

---

src/app/controllers/admin/presenters_controller.rb
src/app/views/admin/presenters/edit.html.erb
src/app/views/admin/sessions/edit.html.erb
src/spec/controllers/admin/presenters_controller_spec.rb

It is possible to create a session without a presenter from the admin
page.  Once you do that, you may want to add the presenter's name at a
latter time.  In order to do that we need three changes:
1. Create a clickable link by showing alternate text when name is
missing.
2. Changing the link to get to the particpant edit page.
3. Allowing the admin presenter controller to accept some missing values
(e.g. email)

Allow a way to add a name to presenters that don't have one

---

src/app/controllers/admin/sessions_controller.rb
src/spec/controllers/admin/sessions_controller_spec.rb

Presently if you make a bunch of sessions with a blank name, they are
all assigned to the same presenter.  This poses a problem if you later
want to change the presenters name.  It would change the name for all
unassigned sessions. This makes one presenter for each unassigned
session. This allows us to set different names at a later time.

Make multiple blank users rather than just one.

---

src/spec/controllers/schedules_controller_spec.rb
src/spec/factories/session.rb
src/spec/models/sessions_json_builder_spec.rb

If Lukeness is required, make it explicit.  This fixes a problem when
you try to use the session factory twice and it complains that Luke's
email is already taken.
Sorry @look

Remove the implied Lukeness from the factory session

---

src/db/migrate/20100414215724_create_sessions.rb
src/db/migrate/20100414224830_create_categories.rb
src/db/migrate/20100414231806_create_categorizations.rb
src/db/migrate/20100423205652_create_participants.rb
src/db/migrate/20100423214500_create_attendances.rb
src/db/migrate/20110414023923_create_events.rb
src/db/migrate/20110414025659_add_event_to_session.rb
src/db/migrate/20120325234743_create_timeslots.rb
src/db/migrate/20120326003621_add_timeslot_to_session.rb
src/db/migrate/20120326004820_create_rooms.rb
src/db/migrate/20120326004834_add_room_to_session.rb
src/db/migrate/20120330060456_add_presentations.rb
src/db/migrate/20120401214321_create_presenter_timeslot_restrictions.rb
src/db/migrate/20120403022345_make_timeslot_use_timestamp.rb
src/db/migrate/20120404031433_add_summary_to_session.rb
src/db/migrate/20130224225306_make_participant_authenticatable.rb
src/db/migrate/20130304053159_add_level_to_sessions.rb
src/db/migrate/20130304053929_create_levels.rb
src/db/migrate/20150319011702_add_perishable_token_to_users.rb
src/db/migrate/20150414022055_create_settings.rb
src/db/migrate/20150911192254_add_schedulable_and_title_to_timeslot.rb
src/db/migrate/20150920192518_add_schedulable_to_room.rb
src/db/migrate/20160319173736_add_more_attributes_to_participant.rb
src/db/migrate/20160420042853_add_manually_scheduled_to_sessions.rb

Otherwise you can't run `rake db:migrate` on rails 5.1

Add version number to migrations

---

src/app/assets/stylesheets/shared.css.scss

Session titles were being cut off due to the padding for the buttons that appear when you're signed in and can express your interest.

Fix cut-off session titles

---

src/db/migrate/20100414215724_create_sessions.rb
src/db/migrate/20100414224830_create_categories.rb
src/db/migrate/20100414231806_create_categorizations.rb
src/db/migrate/20100423205652_create_participants.rb
src/db/migrate/20100423214500_create_attendances.rb
src/db/migrate/20110414023923_create_events.rb
src/db/migrate/20110414025659_add_event_to_session.rb
src/db/migrate/20120325234743_create_timeslots.rb
src/db/migrate/20120326003621_add_timeslot_to_session.rb
src/db/migrate/20120326004820_create_rooms.rb
src/db/migrate/20120326004834_add_room_to_session.rb
src/db/migrate/20120330060456_add_presentations.rb
src/db/migrate/20120401214321_create_presenter_timeslot_restrictions.rb
src/db/migrate/20120403022345_make_timeslot_use_timestamp.rb
src/db/migrate/20120404031433_add_summary_to_session.rb
src/db/migrate/20130224225306_make_participant_authenticatable.rb
src/db/migrate/20130304053159_add_level_to_sessions.rb
src/db/migrate/20130304053929_create_levels.rb
src/db/migrate/20150319011702_add_perishable_token_to_users.rb
src/db/migrate/20150414022055_create_settings.rb
src/db/migrate/20150911192254_add_schedulable_and_title_to_timeslot.rb
src/db/migrate/20150920192518_add_schedulable_to_room.rb
src/db/migrate/20160319173736_add_more_attributes_to_participant.rb
src/db/migrate/20160420042853_add_manually_scheduled_to_sessions.rb
src/db/schema.rb

* Specifying the Rails release that the migrations were written for is necessary.  Without the migration script updates, the following message appeared:
```
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for
```
* These changes in this pull request allow the "rails db:migrate" command to proceed and allow the tests to pass.
* No other changes are involved in this pull request.  I will make a number of small pull requests for other changes.

Updated the migration scripts

---

README.md

Changed "herok run rake db:seed" to "heroku run rake db:seed"

Corrected typo in README.md file

---

src/config/environments/development.rb
src/config/environments/test.rb

Removing the SMTP/Mandrill settings in src/config/environments/development.rb allows me to try out the password reset feature in the development environment.  Removing these settings in src/config/environments/test.rb is necessary for providing tests of the password reset feature.

Removed the SMTP/Mandrill settings the dev and test environments

---

src/lib/tasks/app.rake

The output of this is that we should have 15 rooms created when we run `rails app:create_rooms` to be used by `rails app:assign_rooms`.

Update rooms for Minnebar18

---

src/Gemfile
src/Gemfile.lock
src/spec/spec_helper.rb

Poltergeist is long defunct, and was breaking specs. Switched to Capybara default driver. Specs now all pass again. Yay!
`rails spec` now launches Firefox for integration tests, which is…surprising the first time, but probably fine.

Ripped out poltergeist; using default Capybara driver

---

src/app/models/session.rb
src/app/views/participants/show.html.erb
src/spec/features/participant_show_spec.rb

I added an integration test of the participant show page, and all tests pass.  I updated the for_current_event scope in src/app/models/session.rb so that it wouldn't result in an error message when there are no events.  The only change I made in src/app/views/participants/show.html.erb was to correct a typo.

The participant show page works even when there are no events

---

src/Gemfile
src/Gemfile.lock
src/spec/controllers/admin/presenters_controller_spec.rb
src/spec/factories.rb
src/spec/factories/category.rb
src/spec/factories/event.rb
src/spec/factories/participant.rb
src/spec/factories/presenter_timeslot_restriction.rb
src/spec/factories/room.rb
src/spec/factories/session.rb
src/spec/factories/timeslot.rb
src/spec/features/display_schedule_spec.rb
src/spec/models/timeslot_spec.rb
src/spec/spec_helper.rb

`FactoryGirl` has been deprecated for a long time. This PR upgrades from `FactoryGirl` => `FactoryBot`.
* Switch from `factory_girl_rails` => `factory_bot_rails`
* Convert static attribute definitions to dynamic in factories (see https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11).

Upgrade FactoryGirl to FactoryBot

---

src/app/controllers/presentations_controller.rb
src/spec/controllers/presentations_controller_spec.rb

This is a follow up to https://github.com/minnestar/sessionizer/pull/305, which broke the controller tests.
This allows for both `:id` and `:name` params to be passed into the controller. When a presenter is found, an `:id` is passed, but if the user hits enter with just a text string search, we still need to handle that case, hence why `:name` is still permitted.

Update presentations controller logic and spec

---

app/assets/stylesheets/shared.css.scss
app/controllers/attendances_controller.rb
app/controllers/participants_controller.rb
app/controllers/sessions_controller.rb
app/controllers/user_sessions_controller.rb
app/helpers/participants_helper.rb
app/mailers/notifier.rb
app/models/participant.rb
app/views/layouts/application.html.erb
app/views/notifier/participant_email_confirmation.html.erb
app/views/notifier/password_reset_instructions.html.erb
app/views/participants/edit.html.erb
app/views/sessions/_email_confirmation.html.erb
app/views/sessions/new.html.erb
app/views/sessions/show.html.erb
config/environments/test.rb
config/routes.rb
db/migrate/20250209180413_add_email_confirmed_at_to_participants.rb
db/schema.rb
spec/controllers/attendances_controller_spec.rb
spec/controllers/participants_controller_spec.rb
spec/features/interest_gathering_spec.rb
spec/features/manage_sessions_spec.rb
spec/features/manage_your_profile_spec.rb
spec/features/sign_in_and_out_spec.rb
spec/support/authentication_support.rb

This is part of a larger effort to mitigate and prevent spam on the platform.
- Other small changes
- Add support for `flash[:alert]` (orange)
- Change `@user` references to `@participant` for consistency
- Update tests & add test cases for new functionality
- Update `respond_with(@participant` references due to collisions with URL helpers
https://github.com/user-attachments/assets/70c01750-30e4-4bb7-94bd-3c04b8796715
https://github.com/user-attachments/assets/abbea11b-05a6-45b9-b9b2-6cd9f1ea09b2
https://github.com/user-attachments/assets/d2ac8b80-02f6-4a9a-8f88-6e9b08a887f9

Confirm participant emails

---

app/assets/stylesheets/participant.scss
app/controllers/participants_controller.rb
app/models/participant.rb
app/views/participants/new.html.erb
spec/controllers/participants_controller_spec.rb

addresses issue #262 
* creates a fake form field only visible to bots. the form field is called `contact_details` in order to appear realistic. it is positioned off screen, is completely opaque, and is removed from the tabindex. 
* enforces absence of `contact_details` field at the controller level. if a user tries to submit the form with `contact_details` present, the account cannot be created.
there is an rspec that tests that accounts cannot be created when this field is provided. 
to test manually: 
* ensure that the `contact_details` field is not announced by a screen reader
* ensure that a user cannot see or navigate to the `contact_details` field
* ensure that a user can sign up normally
* confirm that there are no visual changes to the form on this branch.
to manually test the …

add honeypot address field to new account sign up form

---

app/mailers/notifier.rb
app/views/notifier/participant_email_confirmation.html.erb
app/views/notifier/password_reset_instructions.html.erb
app/views/sessions/new.html.erb
app/views/shared/_footer.html.erb

Small tweaks to wording, content, and styling that Meg noticed
* Password resets
- Update subject line
- Update body content
* Email confirmations
- Add team sign off
* Footer
- Update styles, add horizontal line
- Add contact us section
- Reorder content
* Add session page
- Update max session length `45` => `40` min

Update wording, content and styles for clarity

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb

Use dynamic content from `Event.current_event` instead of static values for the meta tag description.

Use dynamic meta description content from current event

---

app/admin/dashboard.rb
app/admin/events.rb
app/admin/participants.rb
app/admin/sessions.rb
app/models/attendance.rb
app/models/presentation.rb
app/models/room.rb
app/models/session.rb
app/models/timeslot.rb
db/migrate/20250330143647_add_counter_caches_to_events.rb
db/migrate/20250330164250_add_counter_caches_to_sessions.rb
db/migrate/20250330172156_add_counter_caches_to_participants.rb
db/schema.rb
spec/factories/event.rb
spec/factories/session.rb

The new admin panel is in place, at a barebones level, and with that includes a few n+1 queries (on the events and dashboards pages). This PR fixes that by introducing counter caches and using them to make those columns sortable where applicable.
----
Note that the following commands to reset counter cache _have been included_ in the migrations to add `*_count` columns to each of the models. I figure that's the best/easiest way to ensure they get run post migration, without having to do it manually.
```
Event.find_each { |event| Event.reset_counters(event.id, :sessions, :rooms, :timeslots) }
Session.find_each { |session| Session.reset_counters(session.id, :attendances) }
execute <<-SQL
UPDATE participants 
SET presentations_count = (
SELECT COUNT(*)
FROM presentations
WHERE …
```

Add counter caches to prevent admin panel n+1 queries

---

app/admin/dashboard.rb
app/admin/events.rb
app/admin/rooms.rb
app/admin/settings.rb
app/admin/timeslots.rb

This gets us closer to [feature parity with the legacy admin panel](https://github.com/minnestar/sessionizer/issues/321).
* Add `Settings` to admin panel
* Add `Timeslots` to admin panel (`belongs_to :event`)
* Add `Rooms` to admin panel (`belongs_to :event`)
* Update event info & links to make things easily navigable

Add settings, timeslots, and rooms to admin panel

---

app/admin/dashboard.rb
app/admin/events.rb
app/admin/rooms.rb
app/admin/sessions.rb
app/admin/timeslots.rb
app/models/session.rb
db/migrate/20250330143647_add_counter_caches_to_events.rb
db/migrate/20250330164250_add_counter_caches_to_sessions.rb
db/migrate/20250412161057_add_canceled_at_to_sessions.rb
db/schema.rb

This makes it possible for admins to cancel sessions from the admin panel, without hard-deleting or soft-deleting (by entering a negative `event_id`).
**Screenshots**
**Demo**
https://github.com/user-attachments/assets/fbe64c5d-b723-4bc5-a54a-24d16930b11a

Allow canceling sessions from admin panel
