- src/app/controllers/admin/admin_controller.rb
This is necessary to actually use the admin.
> move to new Heroku SSL domain

- src/app/controllers/sessions_controller.rb
- src/spec/controllers/sessions_controller_spec.rb
Fixes #75. 
I think the build failures are due to the switch to the non-editable front-page and can be ignored.
> Make SessionsController#index respond to JSON again

- src/app/models/timeslot.rb
- src/spec/factories/presenter_timeslot_restriction.rb
- src/spec/models/timeslot_spec.rb
> Destroy PresenterTimeslotRestriction when Timeslot is destroyed.

- src/app/assets/stylesheets/schedule.css.sass
- src/app/controllers/admin/timeslots_controller.rb
- src/app/models/event.rb
- src/app/models/timeslot.rb
- src/app/views/admin/timeslots/edit.html.erb
- src/app/views/admin/timeslots/index.html.erb
- src/app/views/schedules/index.html.haml
- src/config/routes.rb
- src/db/migrate/20150911192254_add_schedulable_and_title_to_timeslot.rb
- src/db/schema.rb
- src/lib/scheduling/context.rb
- src/lib/tasks/app.rake
- src/spec/controllers/admin/timeslots_controller_spec.rb
- src/spec/factories/timeslot.rb
- src/spec/models/timeslot_spec.rb
This allows us to add sessions like Breakfast, Session 0, Lunch, Beer
without having to fiddle with the code.
> Add non-schedulable sessions as DB objects

- src/app/helpers/application_helper.rb
- src/app/views/pages/_aside.html.erb
- src/spec/features/manage_sessions_spec.rb
> Add the create session button to the landing page

- src/app/controllers/schedules_controller.rb
- src/app/views/schedules/_header.html.haml
- src/lib/tasks/app.rake
Some fairly innocuous changes related to 7 sessions, new rooms, etc.
Going to just merge my own here to keep things moving.
> Minnebar 11 schedule setup

- src/Gemfile.lock
- src/app/models/participant.rb
- src/app/models/session.rb
- src/bin/pull-database-from-production
- src/db/migrate/20160420042853_add_manually_scheduled_to_sessions.rb
- src/lib/scheduling/context.rb
- src/lib/scheduling/schedule.rb
- src/lib/scheduling/session_set.rb
- src/lib/tasks/app.rake
I had a bunch of local scheduler tweaks dangling from last year. I used these to generate the schedule, and apparently meant to merge them after the event but forgot. I’m opening this PR so that I don’t forget this time!
> Scheduler improvements

- src/config/routes.rb
- src/db/schema.rb
This allows us to dynamically toggle the schedule/sessions as the landing
page.
> Fixes the routes override of the admin configuration checkbox 

- src/app/models/session.rb
- src/app/views/schedules/index.html.haml
- src/db/migrate/20170324203935_add_manual_attendance_estimate.rb
- src/db/schema.rb
- src/lib/scheduling/context.rb
- src/lib/scheduling/person.rb
- src/lib/scheduling/schedule.rb
- src/lib/scheduling/session_set.rb
- src/lib/tasks/app.rake
In this PR:
- Support for manual override of session size when assigning rooms
- Support for incremental scheduling of additional sessions (with some local hackery; still needs work to be more usable)
- Poor Georgia
> More scheduling tools

- src/app/assets/stylesheets/sessions.scss
- src/app/views/admin/sessions/_session.html.erb
- src/app/views/admin/sessions/index.html.erb
This is only on the admin page.
> Show the sessions in a table

- src/config/environments/development.rb
- src/config/environments/production.rb
- src/config/environments/test.rb
- src/config/secrets.yml
Mandrill is now a paid mailchimp add-on: https://blog.mailchimp.com/important-changes-to-mandrill/  😞
> Use more generic smtp variables

- .gitignore
- vagrant/Vagrantfile
- vagrant/ansible/development.yml
A little love for Vagrant/Ansible. This allows the Ansible provisioning to complete & the Rails app to start cleanly.
Tested w/Vagrant 2.0.2, Ansible 2.4.3.0, VirtualBox 5.2.8 on macOS Sierra.
> Vagrant updates

- src/app/controllers/user_sessions_controller.rb
- src/app/views/user_sessions/new.html.erb
- src/spec/features/sign_in_and_out_spec.rb
* Add a 'Remember me' checkbox to login screen so UserSession is remembered across sessions
> Add Remember me checkbox to login page

- src/Gemfile
- src/Gemfile.lock
- src/app/controllers/admin/sessions_controller.rb
- src/app/controllers/schedules_controller.rb
- src/app/views/admin/events/show.html.erb
- src/spec/controllers/admin/sessions_controller_spec.rb
- src/spec/controllers/schedules_controller_spec.rb
- src/spec/factories/session.rb
- src/spec/models/sessions_json_builder_spec.rb
I'd like to rebase this after #160 is merged.
> Sort sessions

- src/spec/models/session_spec.rb
Tests of Session.swap_rooms and Session.swap_timeslot_and_room are added.
> Added tests of session swapping in src/spec/models/session_spec.rb

- src/app/controllers/admin/sessions_controller.rb
- src/app/controllers/sessions_controller.rb
- src/app/views/admin/sessions/edit.html.erb
- src/app/views/sessions/_form.html.erb
- src/config/routes.rb
Admins can delete any session or the owner can delete the session, and there's a confirmation.
> Add session delete capability fixes #175

- src/app/assets/stylesheets/shared.css.scss
- src/app/views/categories/show.html.erb
- src/app/views/layouts/application.html.erb
- src/app/views/pages/_sessions.html.erb
> Improve visuals for flash messaging

- src/app/views/admin/sessions/edit.html.erb
- src/app/views/sessions/_form.html.erb
Quick change to prevent this from happening, we can add the delete button back later fixes #253
> Remove session delete button for the time being

- src/app/models/participant.rb
- src/app/models/session.rb
- src/bin/pull-database-from-production
- src/bin/schedule
- src/config/initializers/core_ext.rb
- src/lib/scheduling/context.rb
- src/lib/scheduling/schedule.rb
- src/lib/tasks/app.rake
Folding in older local updates to scheduler + multi-day scheduling stuff
> Scheduler and admin tweaks

- src/app/assets/stylesheets/schedule.css.sass
- src/app/controllers/schedules_controller.rb
- src/app/helpers/schedules_helper.rb
- src/app/views/schedules/_header.html.haml
- src/app/views/schedules/index.html.haml
- src/bin/schedule
- src/spec/helpers/schedules_helper_spec.rb
- DRAFT warning when previewing schedule
- Better sessions ordering when rooms unassigned
- Updated schedule header links for 2023 Minnebar
- Tweak to scheduling script
> Schedule view updates
